Update gen_utils.py
Fix bug, expression.columns has nan, and it cann't be removed by `i is not np.nan`,  and nan is float, then raise AttributeError: 'float' object has no attribute 'upper'.